### ISSUE TITLE
Crash when switching between grayscale and black and white

### ISSUE THREAD

**Issue by fuglaro** [Timendus/thumby-grayscale#10]
Observable in the BrightnessTest

```
MicroPython v1.19.1 on 2022-06-18; Raspberry Pi Pico with RP2040
Type "help()" for more information.
>>> 
Traceback (most recent call last):
  File "<stdin>", line 49, in <module>
  File "thumbyGrayscale.py", line 401, in disableGrayscale
  File "thumbyGrayscale.py", line 320, in init_display
TypeError: 'type' object isn't subscriptable
>
------------------------------------------------------
```

**Comment by fuglaro** [comment]
Looks like it might have something to do with invert previously being used.
